### ISSUE TITLE
New version on the puppet forge ?

### ISSUE THREAD

**Issue by sbadia** [nesi/puppet-rrd#5]
Hi!
It seems that the `0.1.2` version doesn't include the fix 3ab43557db8a105325c52cdcef1d990f9796cf4b, it's possible to publish a new version on the puppet forge (with possibly a tag in git and a changelog file :-)).

Thanks in advance!!

**Comment by Aethylred** [comment]
Thanks, doing a merge and sorting it out. 1.3 will be up soon.

**Comment by sbadia** [comment]
Thanks!
